# Generated by Django 5.2.1 on 2026-05-06 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TableProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام جدول")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعال"), ("archived", "بایگانی")],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="به روز شده در"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربران مجاز",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول پروژه",
                "verbose_name_plural": "جدول های پروژه",
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=500, verbose_name="عبارت")),
                (
                    "normalized_phrase",
                    models.CharField(
                        editable=False, max_length=500, verbose_name="عبارت نرمال شده"
                    ),
                ),
                (
                    "abjad_value",
                    models.PositiveIntegerField(default=0, verbose_name="عدد ابجد"),
                ),
                (
                    "prime_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="چندمین عدد اول"
                    ),
                ),
                (
                    "digit_root",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ریشه عدد"
                    ),
                ),
                (
                    "abjad_sum",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مجموع عدد ابجد"
                    ),
                ),
                (
                    "parity_label",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="زوج یا فرد"
                    ),
                ),
                (
                    "parity_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="چندمین زوج فرد"
                    ),
                ),
                (
                    "letter_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد حروف"),
                ),
                (
                    "dot_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد نقطه"),
                ),
                (
                    "pronounced_value",
                    models.PositiveIntegerField(default=0, verbose_name="عدد ملفوظی"),
                ),
                (
                    "alif_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد الف"),
                ),
                (
                    "abjad_saghir",
                    models.PositiveIntegerField(default=0, verbose_name="ابجد صغیر"),
                ),
                (
                    "breakdown",
                    models.TextField(blank=True, verbose_name="تبدیل حرف به عدد"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="به روز شده در"),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(default=0, verbose_name="ردیف"),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت بررسی",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="یادداشت بررسی"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت کننده",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_project_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی کننده",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="entries.tableproject",
                        verbose_name="جدول پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد پروژه",
                "verbose_name_plural": "رکوردهای پروژه",
                "ordering": ["row_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="MainEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=500, verbose_name="عبارت")),
                (
                    "normalized_phrase",
                    models.CharField(
                        editable=False, max_length=500, verbose_name="عبارت نرمال شده"
                    ),
                ),
                (
                    "abjad_value",
                    models.PositiveIntegerField(default=0, verbose_name="عدد ابجد"),
                ),
                (
                    "prime_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="چندمین عدد اول"
                    ),
                ),
                (
                    "digit_root",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ریشه عدد"
                    ),
                ),
                (
                    "abjad_sum",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مجموع عدد ابجد"
                    ),
                ),
                (
                    "parity_label",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="زوج یا فرد"
                    ),
                ),
                (
                    "parity_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="چندمین زوج فرد"
                    ),
                ),
                (
                    "letter_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد حروف"),
                ),
                (
                    "dot_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد نقطه"),
                ),
                (
                    "pronounced_value",
                    models.PositiveIntegerField(default=0, verbose_name="عدد ملفوظی"),
                ),
                (
                    "alif_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد الف"),
                ),
                (
                    "abjad_saghir",
                    models.PositiveIntegerField(default=0, verbose_name="ابجد صغیر"),
                ),
                (
                    "breakdown",
                    models.TextField(blank=True, verbose_name="تبدیل حرف به عدد"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="به روز شده در"),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        default=0, unique=True, verbose_name="ردیف"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_main_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منتشر کننده",
                    ),
                ),
                (
                    "source_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_entry",
                        to="entries.projectentry",
                        verbose_name="رکورد مبدا",
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_entries",
                        to="entries.tableproject",
                        verbose_name="پروژه مبدا",
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد جدول اصلی",
                "verbose_name_plural": "رکوردهای جدول اصلی",
                "ordering": ["row_number", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectentry",
            constraint=models.UniqueConstraint(
                fields=("project", "row_number"), name="unique_project_row_number"
            ),
        ),
    ]
