# Generated by Django 5.2.1 on 2026-05-06 16:52

from django.db import migrations


def recompute_used_letters(apps, schema_editor):
    abjad_map = {
        "ا": 1, "ب": 2, "ج": 3, "د": 4, "ه": 5, "و": 6, "ز": 7, "ح": 8, "ط": 9,
        "ی": 10, "ک": 20, "ل": 30, "م": 40, "ن": 50, "س": 60, "ع": 70, "ف": 80,
        "ص": 90, "ق": 100, "ر": 200, "ش": 300, "ت": 400, "ث": 500, "خ": 600,
        "ذ": 700, "ض": 800, "ظ": 900, "غ": 1000, "آ": 1, "ء": 1, "ئ": 1,
        "ة": 400, "أ": 1, "ؤ": 6,
    }
    sort_index = {char: index for index, char in enumerate(abjad_map.keys())}
    translation = str.maketrans({"ي": "ی", "ى": "ی", "ك": "ک", "\u200c": " ", "\u200f": "", "\u200e": "", "\ufeff": ""})

    def normalize(phrase):
        phrase = (phrase or "").translate(translation)
        return " ".join(phrase.split()).strip()

    def compute(phrase):
        unique_letters = {char for char in normalize(phrase) if char in abjad_map}
        ordered_letters = sorted(unique_letters, key=lambda char: (-abjad_map[char], sort_index.get(char, 9999), char))
        return len(ordered_letters), " - ".join(ordered_letters)

    for model_name in ("ProjectEntry", "MainEntry"):
        model = apps.get_model("entries", model_name)
        for item in model.objects.all():
            item.unique_letter_count, item.used_letters = compute(item.phrase)
            item.save(update_fields=["unique_letter_count", "used_letters"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "entries",
            "0002_mainentry_unique_letter_count_mainentry_used_letters_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(recompute_used_letters, migrations.RunPython.noop),
    ]
