# Generated by Django 5.0.7 on 2026-05-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_recompute_used_letters_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("update", "ویرایش"), ("delete", "حذف")],
                        max_length=20,
                        verbose_name="نوع تغییر",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("project_entry", "رکورد پروژه"),
                            ("main_entry", "رکورد جدول اصلی"),
                            ("table_project", "جدول پروژه"),
                            ("user", "کاربر"),
                        ],
                        max_length=30,
                        verbose_name="مدل هدف",
                    ),
                ),
                (
                    "target_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه هدف"
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان هدف"
                    ),
                ),
                (
                    "snapshot_before",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="وضعیت قبل"
                    ),
                ),
                (
                    "snapshot_after",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="وضعیت بعد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان تغییر"),
                ),
                (
                    "undone_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بازگشت"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام دهنده",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بازگرداننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تغییر اخیر",
                "verbose_name_plural": "تغییرات اخیر",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
